version: '3'

services:
  app:
    image: node:18-alpine
    container_name: d-tapp-dv01-frontend-challenge
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4173:4173"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run build && pnpm preview --host"
    stdin_open: true
    tty: true
