#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/shared

echo "Let's get this party started! 🎉 Starting up the Docker container... 🍕"
echo "🧹 Cleaning up old containers... 🧽"
docker-compose down
docker-compose up --build -d

echo "⏳ Waiting for the container to warm up... ⏳"
RETRIES=0
MAX_RETRIES=30
until curl --silent --fail http://localhost:4173; do
  if (( RETRIES == MAX_RETRIES )); then
    echo "🚨 Timeout reached! The app is not responding. Please check the logs."
    exit 1
  fi
  (( RETRIES++ ))
  echo "💤 Waiting for app to be responsive... Attempt $RETRIES/$MAX_RETRIES"
  sleep 2
done

echo "Opening your browser... 🍻"
if command -v xdg-open &> /dev/null
then
  echo "Opening in the default browser... 😎"
  xdg-open http://localhost:4173
elif command -v open &> /dev/null
then
  echo "Opening in the default browser... 😁"
  open http://localhost:4173
else
  echo "Oops! Could not detect the default browser. 🤷‍♂️"
fi

echo "💰 Daniel's frontend challenge submission is now live and thriving! 🌟"
